compiler-research/CppInterOp

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/ScopeReflectionTest.cpp
- unittests/InterOp/VariableReflectionTest.cpp
This PR adds functions that are necessary to fix class static variables in cppyy.
@vgvassilev the address of class static variables is not being returned. Offending lines of code:
https://github.com/compiler-research/InterOp/blob/515ef931fc6db076bc4c414a54e1b24a8c8b2858/lib/Interpreter/InterOp.cpp#L794-L797
The above code returns nullptr. This test case has been added to GetVariableOffset test.
> Fix class static variables

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/TypeReflectionTest.cpp
Uses an enum `DimensionValue::UNKNOWN_SIZE` to denote the size of these types.
I have used a `namespace` instead of an `enum class` for `DimensionValue` so that it can be implicitly converted to and from long int.
> Add support for ArrayTypes that are not ConstantArrayType in GetDimensions

- CMakeLists.txt
We try to fix some issues in searching packages LLVM, Clang and optional Cling.
We define some default values of paths as LLVM_DIR, Clang_DIR and Cling_DIR.
Also we "equalize" usage of PATHS and HINTS for search packages.
> Try to fix LLVM/Clang/Cling search package process

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/CMakeLists.txt
- unittests/InterOp/InterpreterTest.cpp
This patch drops the unused resource-dir parameter and improves the implementation of GetScope allowing it to return more found declarations such as function declarations.
> Teach InterOp::CreateInterpreter to take arguments.

- include/clang/Interpreter/InterOp.h
- include/clang/Interpreter/InterOpInterpreter.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/FunctionReflectionTest.cpp
These interfaces are responsible for object creation and destruction calling the relevant constructors/destructors.
Fixes #16. Fixes #17.
> Implement construct and destruct interfaces.

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/FunctionReflectionTest.cpp
- unittests/InterOp/InterpreterTest.cpp
- unittests/InterOp/ScopeReflectionTest.cpp
- unittests/InterOp/TypeReflectionTest.cpp
- unittests/InterOp/Utils.cpp
- unittests/InterOp/Utils.h
- unittests/InterOp/VariableReflectionTest.cpp
This patch removes the external calls to getInterpreter/getSema in favor of storing them as static variables. That improves the ABI resilience of the API.
> IsComplete should try to instantiate a type if it was a template.

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
I have added function definitions as Doxygen-style comments, based on the CppInterop information session between Baidyanath and Krishna.
Please review if my understanding was correct in these definitions (since I'm new to the domain).
Requested Reviewers: @vgvassilev  @sudo-panda
> Added Comments for CppInterOp's Doxygen based documentation

- .github/workflows/ci.yml
similar to the changes done in https://github.com/vgvassilev/clad/pull/599
> Fix git-clang-format run when PR not on top of master

- unittests/InterOp/ScopeReflectionTest.cpp
This should fix our valgrind reports.
> Do not reset the interpreter after we took the ASTContext.

- include/clang/Interpreter/InterOp.h
- lib/Interpreter/InterOp.cpp
- unittests/InterOp/ScopeReflectionTest.cpp
This routine should be used only in cases where we cannot do anything else. It takes the string and tries to force the compiler to instantiate by requesting the address to the function.
> Implement a slow string-based function template instantiation.

- include/clang/Interpreter/Compatibility.h
- include/clang/Interpreter/CppInterOp.h
- include/clang/Interpreter/CppInterOpInterpreter.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/JitTest.cpp
This patch allows users of CppInterOp to rewire things like printf to enable rich displays, for example.
> Implement the ability to swap functions in the JIT.

- docs/UsingCppInterOp.rst
#120 Address the issue mentioned
> Update docs with detailings in usage of CppInterOp

- include/clang/Interpreter/Compatibility.h
This patch should resolve an issue in xeus-clang-repl with clad.
> Load the compiler instance plugins.

- lib/Interpreter/CMakeLists.txt
This should fix the failures in the clangdev conda package and CppInterOp.
> Add missing dependencies for LLVM_LINK_LLVM_DYLIB

- cmake/CppInterOp/CppInterOpConfig.cmake.in
- lib/Interpreter/Compatibility.h
Stopped Cuda library been loaded when on Apple
Add .dylib option for when on MacOS
> Added fixes which caused issues building on Apple Silicon

- .github/workflows/ci.yml
- lib/Interpreter/CppInterOpInterpreter.h
- patches/llvm/clang17-1-NewOperator.patch
Added section that will run tests on arm osx once free tier github runner available  (currently commented out)
Build cppyy and tests on macos as well as linux, and where CppInterOp uses clang-repl as well as cling
Use homebrew provided clang rather than apple provided clang
Test for both clang-repl 16 and 17 for both macos and linux
Update ubuntu runner to be consistent across all Ubuntu runners
> Update macos and ubuntu ci to be more extensive

- docs/UsingCppInterOp.rst
- Reducing cppyy Dependencies
- Code Example
- cppyy components
- cppyy repos (enhanced forks+upstream)
- Credits to Devs
- Further Reading Links
> Added Dpcumentation of cppyy Enhancements and how they relate to LibInterOp

- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/JitTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
- Prepend `_` before looking for symbols
- Currently the interface is not unified and solutions like a global prefix would work better.
> [Symbol Names] Workaround: Mangle names for macOS

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- patches/llvm/clang16-1-Value.patch
PR to add CI build infrastructure + fixes https://github.com/compiler-research/CppInterOp/issues/182
> [CI] Update CI to include a Windows build of CppInterOp + other general CI improvements

- .github/workflows/ci.yml
- README.md
- cmake/modules/GoogleTest.cmake
- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/DynamicLibraryManager.cpp
- lib/Interpreter/DynamicLibraryManager.h
- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
- lib/Interpreter/Paths.cpp
- lib/Interpreter/Paths.h
- unittests/CMakeLists.txt
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/DynamicLibraryManagerTest.cpp
- unittests/CppInterOp/TestSharedLib/CMakeLists.txt
- unittests/CppInterOp/TestSharedLib/TestSharedLib.h
Fix some of the windows build errors, It still won't fully build with just these changes, but it gets it much closer. 
I don't know much of the llvm internal API, but i did switched from some Linux specific function that were failing to build on windows with llvm API like SearchForAddressOfSymbol and real_path.
> Various windows fixes

- .github/workflows/ci.yml
The windows cache artifacts are bigger than the unix ones. This is likely because when building on windows we always need to specify the build configuration.
> Specify the build configuration when building on Windows

- .github/workflows/ci.yml
In this case we open an ssh session for 30 mins.
> [ci] Allow rerunning gh actions with debug logging.

- .github/workflows/ci.yml
- README.md
Adds xeus-clang-repl build to ci
> Add xeus-clang-repl build to ci

- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
It does not seem like this function is used.
> Increase Code Coverage

- .github/workflows/ci.yml
- README.md
- cmake/modules/GoogleTest.cmake
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/TestSharedLib/TestSharedLib.h
@vgvassilev This PR allows for those trying to solve Windows build issues to use a different compiler to MSVC . With these changes I was able to compile CppInterOp and its tests using the Clang compiler. Currently I'm not passing the tests as the header files cannot be found, but I believe this has something to do with the environment variables I have set, and am investigating.
Fixes https://github.com/compiler-research/CppInterOp/issues/175 (provides proof that earlier PR fixed it)
> Add ability to compile CppInterOp and tests on Windows with different compiler

- CMakeLists.txt
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
- unittests/CMakeLists.txt
- unittests/CppInterOp/EnumReflectionTest.cpp
Not all tests pass yet, but they shouldn't crash early with a fatal assert from Clang any more. The library tests could fail in assert builds before because an Error value for a from a Coff symbol in Dyld::BuildBloomFilter was not handled, those errors were actually revealing another issue that search path to load shared libraries to find symbols should be much more restricted instead of PATH environment variable. 
I also added the exporting of some MSVC runtime symbols based on the code from Clings cmake files to try and fix STL symbol errors, but tests still fail because of missing emulated TLS symbols `__emutls_get_address and __emutls_v._Init_thread_epoch` .
Current failing tests are:
```
EnumReflectionTest.GetIntegerTypeFromEnumScope
EnumReflectionTest.GetIntegerTypeFromEnumType …
```
> Windows test fixes

- .github/workflows/ci.yml
- README.md
@vgvassilev The non cppyy or xeus-clang-repl jobs for osx and Ubuntu are redundant. They don't do anything that the cppyy and xeus-clang-repl jobs don't (there was one small valgrind dependence for Ubuntu but this has been removed in this PR). I have removed them so that free Github runner minutes are not wasted, and so we can run through the osx jobs quicker (the maximum number of concurrent osx jobs allowed is 5, so we are currently have to wait longer than necessary for osx PR jobs to run).
> Remove redundant ci jobs

- .github/workflows/ci.yml
- CMakeLists.txt
- environment-wasm-build.yml
- environment-wasm.yml
The purpose of this PR is to add wasm support to CppInterOp
Fixes https://github.com/compiler-research/CppInterOp/issues/183
> [CI] Add wasm support to CI for osx and Linux

- CMakeLists.txt
In short we use variables which require including `GNUInstallDirs` but we are expecting somebody else to include it for us.
See llvm/llvm-project#83802
> [cmake] Work around a bug in the llvm config.

- .github/workflows/ci.yml
- cmake/CppInterOp/CppInterOpConfig.cmake.in
The purpose of this PR is to find the modifications to CppInterOp needed so that the wasm build of xeus-cpp in PR https://github.com/compiler-research/xeus-cpp/pull/14 can pass.
> [cmake] Modify cmake config file to set correct suffix and prefix for library 

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/InterpreterTest.cpp
This is useful when deployed CppInterOp needs to create an interpreter. Often the interpreter itself cannot use the clang toolchain logic to discover both the resource-dir and the include paths. This is because CppInterOp is a library and usually put in the `lib` folder whereas the toolchain logic expects things to be relative to the `bin` folder.
In such setups, we can ask CppInterOp to detect the resource directory by asking clang about it. In the same vain, of finding C and C++ headers we can ask the system compiler about the include paths.
> Implement detection of resource and include dirs.

- .clang-tidy
- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
This patch offers a single interface for instantiation of class, function and variable templates. That would simplify user code where we do not need to care what is the underlying template pattern (most of the time).
> Consolidate the template instantiation logic.

- unittests/CppInterOp/ScopeReflectionTest.cpp
renames missed name change in ScopeReflectionTest (PR #128)
> Fix usage of InstantiateTemplate

- .github/workflows/ci.yml
This PR makes running emscripten_wasm dependent on sucessfull run of build in ci. This should reduce ci resources being used uncessarily, to be used by other PRs in the organisation.
> Make running emscripten_wasm dependent on sucessfull run of build in ci

- .github/workflows/ci.yml
@vgvassilev This should reduce the bot lag as much as https://github.com/compiler-research/CppInterOp/pull/226 while keeping all the jobs.
> [ci] Reduce bot lag by building cache first

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
This PR consolidates interfaces in CppInterOp that allows:
- Exposes information required for template function scope proxy creation -  arg types, method counts, names
- Perform template function lookups using `clang::LookupResult`
- Updates existing interfaces to also handle FunctionTemplateDecl*
- Improves the instantiation process
- Enables auto instantiation and a basic overload selection mechanism in `BestTemplateFunctionMatch`
> Enable template features

- unittests/CppInterOp/FunctionReflectionTest.cpp
This tests both interfaces (GetClassMethods, GetFunctionTemplatedDecls) that use the GetClassDecls static function simultaneously under the same scope
> Tests for static GetClassDecls

- .github/workflows/ci.yml
@vgvassilev can you merge this PR? It completly removes the osx x86 jobs from the ci. These can be tested from the daily runs of the ci in cppyy-backend.
> Remove osx x86 jobs from ci

- .github/workflows/ci.yml
@vgvassilev can you merge this PR? It reduces the warnings outputted by the ci by updating to the latest version of various Github actions.
> Reduce warnings ci

- .github/workflows/ci.yml
@vgvassilev can you clear the cache, and then manually rerun the workflow of this PR? It should pass, while having a reduced llvm cache, based on the workflow in xeus-clang-repl.
> Reduce cache size

- .github/workflows/ci.yml
@vgvassilev This PR contains 2 commits. One should reduce the size of the llvm cache on Windows. The second changes the options when building llvm on Windows to allow a wasm build of CppInterOp on Windows to be added to the ci in a future PR. To test this PR you will need to clear the Windows builds in the cache, and rerun in workflow manually.
> Reduce windows cache size + add options needed for wasm build of CppInterOp on Windows to llvm cache

- lib/Interpreter/CppInterOp.cpp
Add a cling RAII object to annotate the expected deserialization.
> ForceDeclarationOfImplicitMembers might deserialize

- .github/workflows/ci.yml
- environment-wasm.yml
@vgvassilev This PR adds back what is needed to build xeus-cpp as part of the ci. I consider this PR ready for merging, as it was tested previously. It just wasn't merged at the time as CppInterOp wasn't part of compiler-research/xeus-cpp .
Fixes https://github.com/compiler-research/CppInterOp/issues/257
> Add xeus-cpp build to ci + remove xeus-clang-repl builds from ci

- .github/workflows/ci.yml
This should reduce the warnings and errors from the ci workflow to just those relating to cppyy test runs and Windows CppInterOp test failures.
> Reduce warnings and errors ci

- .github/workflows/ci.yml
This should essentially allow workflow runs to skip over the build_cache matrix stage when the cache exists and doesn't need to be built.
> Speed up build_cache process when not needing to build cache

- .github/workflows/ci.yml
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/CUDATest.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/JitTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
- reverts Python version to 3.10
- Disables specific CppInterOp unit tests causing bad valgrind reports
- Added flag for CUDA test to keep disabled during the runs
> [ci] Fixes for crashes on workflow

- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy-review-post.yml
- .github/workflows/clang-tidy-review.yml
Ths updates the workflows for clang format and clang tidy. This is update the actions to use new versions of llvm components, and to use new action versions due to warnings.
> Update clang format and clang tidy

- .github/workflows/ci.yml
This should allow the pip version error to not appear, while not having the issue introduced in the last PR. Will know for sure once ci has run on this PR.
> Change to python 3.11

- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy-review.yml
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/DynamicLibraryManager.cpp
- lib/Interpreter/Paths.cpp
@vgvassilev This is the PR to correct the bug introduced in clang tidy workflow in https://github.com/compiler-research/CppInterOp/pull/269, found in https://github.com/vgvassilev/clad/pull/883 . Once it is has been found to work in Clad this can be merged immediately.
> Fix clang tidy + remove warnings when building

- .github/workflows/ci.yml
- environment-wasm.yml
Fixes https://github.com/compiler-research/CppInterOp/issues/274
This PR will change it so the wasm builds in the ci occur regardless of the outcome of the non wasm jobs. The reason the dependence was there previously was due to build times being large, but this is no longer the case.
> Run wasm build unconditionally in the ci

- .github/workflows/ci.yml
- README.md
The envirnoment variable for the number of processors on Windows was previous not being calculated correctly, or outputted to the Github envirnoment. This means non of the Windows builds previously were building in parallel. This PR should fix this.
> Fix number of processors environment variable Windows

- .github/workflows/ci.yml
The running of the cppyy test jobs currently takes 30 minutes plus to run in the CppInterOp ci on Ubuntu, but around 10 minutes in the cppyy repo workflow. This PR should address this issue and allow PR workflows to run almost 3 time quicker. It also allows for greater consistency between the repos in what they are running in their respective workflows.
> Speed up running of Ubuntu jobs ci

- .github/workflows/ci.yml
- Part of utilizing suppressions
> [ci] No longer do true for cppyy valgrind

- .github/workflows/ci.yml
This PR is part of the node 16 to node 20 transition. It should stop the warning appearing when the ci runs due to the provision-with-micromamba action.
> Fix warning micromamba envirnoment setup ci

- .github/workflows/ci.yml
@vgvassilev @maximusron can one of you merge this into the main to fix the issue with osx x86 jobs? I know this fix works as I'm currently using it in my PR on treating all warnings as errors.
> Fix bug due to swiftlint osx jobs ci

- .github/workflows/ci.yml
For some reason CMAKE_PREFIX_PATH was hardcoded in the wasm builds. This has been corrected to be dependent on an environment variable.
> Remove hardcoding of CMAKE_PREFIX_PATH wasm build

- .github/workflows/ci.yml
- CMakeLists.txt
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/DynamicLibraryManager.cpp
- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
This PR will add the flag to treat all warnings as errors when building the ci.
Fixes https://github.com/compiler-research/CppInterOp/issues/260
Fixes https://github.com/compiler-research/CppInterOp/issues/234
> Treat all warnings as errors

- include/clang/Interpreter/CppInterOp.h
- Add `__CYGWIN__` to allow it to be built in a cygwin environment
- Only enable default visibility for gcc
- Fix CPPINTEROP_API typos
> Add minor fixes for cross-platform support

- .github/workflows/clang-tidy-review.yml
@vgvassilev This PR makes the same changes to the clang tidy workflow as was made in clad.
> Fix clang tidy review workflow

- environment-wasm.yml
This PR should allow the wasm jobs in the ci to pass again after the changes to the requirements in xeus-cpp
> Fix wasm jobs in ci due to changes in xeus-cpp requirements

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/CppInterOpInterpreter.h
- unittests/CppInterOp/InterpreterTest.cpp
Fixes #69 
I was unsure if to return `std::vector<std::string>` or a single `std::string` with delimiter. I have gone with a single `std::string` with `:` as the delimiter, but it can be changed.
---
With the following changes in the [cppyy](https://github.com/compiler-research/cppyy) library.
```diff
diff --git a/python/cppyy/__init__.py b/python/cppyy/__init__.py
index 53b7e92..441c34c 100644
--- a/python/cppyy/__init__.py
+++ b/python/cppyy/__init__.py
@@ -260,6 +260,11 @@ def add_include_path(path):
raise OSError('No such directory: %s' % path)
gbl.Cpp.AddIncludePath(path)
+def get_include_path():
+    """Get include paths available to Cling."""
+    path = gbl.Cpp.GetIncludePaths()
+    return path.split(":")
+
def add_library_path(path):
"""Add a path to the library search paths …
```
> Implement `GetIncludePaths`

- .github/workflows/ci.yml
PR https://github.com/compiler-research/CppInterOp/pull/298 showed that it is currently not possible to build a wasm version of CppInterOp on Windows. Therefore this PR removes the web assembly build of llvm on Windows from the cache. The cache on the main should be cleared before this PR is merged, and should end up smaller.
> Remove Windows wasm llvm

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
Fixes: [test04_class_read_access](https://github.com/Vipul-Cariappa/cppyy-compiler-research/blob/75be0854fbdb830b597b73377a4f95fe8b2108f3/test/test_datatypes.py#L381-L382) and [test05_class_data_write_access](https://github.com/Vipul-Cariappa/cppyy-compiler-research/blob/75be0854fbdb830b597b73377a4f95fe8b2108f3/test/test_datatypes.py#L444-L445) with one-liner change in cppyy.
> Resolve static attributes of records

- README.md
For newer OS's (Ubuntu 24, Fedora) users run into pip defaulting to the cppyy-cling pypi package instead of using the `libcppyy` and `libcppyy-backend` based on libInterOp. The addition of  `--no-build-isolation` fixes this
> Add cppyy build isolation command in README

- lib/Interpreter/CppInterOp.cpp
Eight previously failing tests pass without any new failing tests in cppyy.
But `EnumReflectionTest.GetEnums` fails from the CppInterOp tests.
It looks like `GetEnums` cannot resolve any `enum`s in the global scope.
> using `getFirstDecl` for `TranslationUnitDecl` for consistent pointers

- lib/Interpreter/Compatibility.h
To also be backported to the root-v1.0 tag
> Use `getExecutionEngine` to obtain the JIT for Cling > LLVM16

- .github/workflows/ci.yml
As done in https://github.com/emscripten-forge/recipes/pull/1385 there are no undefined symbols coming out of a wasm build for cppinterop and hence this flag (`EMCC_CFLAGS='-sERROR_ON_UNDEFINED_SYMBOLS=0'`) is redundant.
> Remove flag as no undefined symbols found while building for wasm

- .github/workflows/ci.yml
- CMakeLists.txt
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/DynamicLibraryManager.cpp
- lib/Interpreter/Paths.cpp
- unittests/CppInterOp/CUDATest.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/JitTest.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
The objective of this PR is to add to the ci a non wasm build of xeus-cpp which runs its various tests. This should allow debugging of the missing symbols needed to make Windows work (discussion here https://github.com/compiler-research/xeus-cpp/issues/144).
> Remove continue-on-error Windows jobs ci

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
I feel like we also need to split the implementation and use an internal shared header for interfaces.
> Refactoring the API for multiple interpreter instance support

- .clang-format
C++14 is stated as the minimum standard acceptable by roots llvm 13 that we use, so I've updated the clang-format file to reflect this standard.
> Change standard clang format to Cpp14

- .gitignore
We do not create any Fortran files during the build process, so seems unneeded to have them in the .gitignore
> Remove Fortran files from .gitignore

- .clang-format
The recent PR which change clang format from Cpp11 to Cpp14 failed. Despite what I read online Cpp14 is not being recognised as an option, so I am reverting to the previous standard.
> Revert back to Cpp11 clang-format

- .github/workflows/ci.yml
Coverage was set to try for all llvm cache builds. Didn't do anything to effect results but needs removing. Coverage was set to true for both llvm 18 and llvm 19 builds of CppInterOp. I've removed the true flag from the llvm 18 build so we have consistent coverage report results going forward.
> Remove random coverage flags ci

- CMakeLists.txt
Fixes bugs in the CMake when built with ROOT, providing the right settings for clang and LLVM options and paths
> [cmake] Support non-standalone builds

- .github/workflows/ci.yml
Currently the osx jobs in the ci are failing due to full Xcode requirement for unxip (see https://github.com/compiler-research/CppInterOp/actions/runs/11645652818/job/32429107514#step:12:175). This package description to me suggests this package is not needed https://formulae.brew.sh/formula/unxip . This PR remove unxip hopefully fixing the issue.
> Remove unxip ci osx

- CMakeLists.txt
- cmake/modules/GoogleTest.cmake
This PR will attempt to update the version of gtest we are using to version 1.15.2 .
Fixes https://github.com/compiler-research/CppInterOp/issues/295
> Update gtest used to v1.15.2

- .github/workflows/ci.yml
Currently we have a warning in the ci about files being overwritten during the brew link stage for openssl. By removing openssl we should stop this warning appearing when the ci runs.
> Remove ci warnings about linking of openssl brew

- .github/workflows/stale-pr-and-issues.yml
This PR makes it so issues and PRs which have had no activity for 90 days will be marked as stale, and will be closed 14 days after that if no further activity.
> Stale issue and PR workflow

- .github/workflows/ci.yml
- environment-wasm-build.yml
This PR will update the ci to match what is done in xeus-cpp, by not using emsdk from conda
> Dont use conda emsdk

- .github/workflows/markdown-linter.yml
- README.md
- docs/ReleaseNotes.md
This PR should add a markdown linter workflow. This workflow can be expanded in future to check other file formats.
> Add markdown linter workflow

- lib/Interpreter/Paths.cpp
- lib/Interpreter/Paths.h
This PR tries to remove what looks like unused code (I couldn't find reference to this code being used in CppInterOp, cppyy-backend,CPyCppyy, cppyy or xeus-cpp). We should see an increase in coverage if this PR works.
> Remove unused code

- .readthedocs.yaml
- docs/DevelopersDocumentation.rst
- docs/conf.py
@vgvassilev This PR may or may not provide a fix for https://github.com/compiler-research/CppInterOp/issues/243 . It fixes the link on my local machine, but that may not necessarily work when deployed.
> Try to fix developer documentation deployment

- docs/UsingCppInterOp.rst
This PR makes some small changes to UsingCppInterOp.rst to reflect the fact that CppInterOp now generates shared library on more than just Linux, and removes reference to patches, instead pointing user to installation instructions.
> Update UsingCppInterOp.rst to not reference use of patches + small other updates

- .github/workflows/ci.yml
When adding the docs jobs in the ci the other day it was forgotten that we need to build the target sphinx-cppinterop too. This PR fixes that.
> Build target sphinx-cppinterop in ci docs job

- .github/workflows/stale-pr-and-issues.yml
@vgvassilev @aaronj0  You may have noticed that a large number of issues got labelled as stale yesterday (PRs will eventually be labelled this too). This PR will add exemptions to the state issue and PR workflow. If you do not want an issue to be labelled as stale, and eventually closed if inactive, then add the 'to-fix' label to the issue. If you want a PR to be made exempt then you should add the 'awaiting-approval' or 'work-in-progress' label to the PR. After merging this PR it may be worth going through out list of issues and PRs and relabelling accordingly.
> Add exemptions to stale-pr-and-issues.yml

- .readthedocs.yaml
- docs/conf.py
@vgvassilev This PR reverts the changes to https://github.com/compiler-research/CppInterOp/pull/372 which were controlling the build process in the hopes of fixing the readthedocs.
> Revert changes to https://github.com/compiler-research/CppInterOp/pull/372

- .github/pull_request_template.md
- CONTRIBUTING.md
This PR adds a basic pull request template to the repo. @vgvassilev @maximusron  This PR is ready for review.
> Added pull_request_template.md

- .github/workflows/ci.yml
This PR updates the ci.yml to use MacOS 15 for the arm osx jobs
> Update ci.yml to use MacOS 15 for arm osx jobs

- .github/workflows/stale-pr-and-issues.yml
Currently the stale pr and issues workflow doesn't process all our issues and PRs due to operations-per-run being 30 by default. I have tripled this so that all our issues and PRs should be processed the next time this workflow runs.
> Increase operations-per-run in stale-pr-and-issues.yml to 90 so more issues and PRs get processed

- .github/workflows/clang-tidy-review-post.yml
- .github/workflows/clang-tidy-review.yml
The git clang workflow currently has a warning to see that soon the ubuntu-latest runners will default to Ubuntu 24.04 .  To stop this I have fixed the version to Ubuntu 22.04 . This workflow will soon be replaced due to the workflow known to be fragile.
> Fix git clang workflow os to Ubuntu 22.04

- docs/conf.py
@vgvassilev This PR will fix the read the docs giving us the developer documentation again. The other day I was fixing the deployment blind as I didn't know about the build logs. Here it is for the most recent build https://readthedocs.org/projects/cppinterop/builds/26507232/  . By expanding the `python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html` command you see we fail due to the following error 
```
CMake Error at CMakeLists.txt:238 (message):
We need either USE_CLING or USE_REPL
```
This PR will fix that by defining that we want to use the repl when building the docs. The build logs explain why we still get some of the documentation, see
```
writing output... [ 14%] …
```
> Fixes read the docs

- .github/workflows/deploy-pages.yml
- README.md
@anutosh491 @vgvassilev This PR should add a Jupyter Lite xeus-cpp demo to CppInterOp. We can use it to demo CppInterOps capability, and can also use it to determine when we have a working emscripten version.
> Add Jupyter-Lite xeus-cpp demo to CppInterOp

- include/clang-c/CXCppInterOp.h
- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/CXCppInterOp.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
- unittests/CppInterOp/Utils.cpp
- unittests/CppInterOp/Utils.h
Since there is a substantial overlap with libclang’s API, I am only exposing the API I currently use in this PR. 
This PR introduces two types, `CXScope` and `CXQualType`, which wrap `TCppScope_t` and `TCppType_t`, respectively. The structure of these two types is the same as libclang's `CXCursor`/`CXType`, with the only difference being that they store a handle to the interpreter instead of a CXTranslationUnit. This paves the way for upstreaming changes to libclang.
> Add a libclang-style C API

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- .github/ISSUE_TEMPLATE/02-feature-request.yml
- .github/ISSUE_TEMPLATE/03-documentation.yml
- .github/ISSUE_TEMPLATE/config.yml
@vgvassilev This PR should improve the quality of issues that people raise for this repo. To get an idea of what happens when people raise issues after this PR, go to my fork and try and raise an issue. People can no longer open blank issues, and instead need to fill in a template issue decided by the yml files inside the issue_template folder. I've tried to make everything in the forms to be mandatory, and should help us debug issues in future as we further develop the forms.
> Add issue templates

- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
`GetDatamembers` now also returns `UsingShadowDecl` that point to `FieldDecl`.
Update `GetUnderlyingScope` to return the target Decl of using statements.
Simplified `CheckVariableAccess` logic.
Towards fixing `test14_protected_access` in cppyy.
> Update `GetDatamembers` and `GetUnderlyingScope` to work with `UsingShadowDecl`

- README.md
This PR fixes a small typo in the build instructions for Windows, based on llvm 17.
> Fix llvm 17 build instructions Windows

- .github/workflows/ci.yml
- .github/workflows/deploy-pages.yml
- patches/llvm/emscripten-clang19-1-CrossCompile.patch
This PR should make the emscripten build of llvm we make in the ci match that in Emscripten forge.
> Improve emscripten llvm build in ci

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
Fixes the calculation of data member offsets of a class C. Where C inherits from multiple classes and these classes themselves inherit from other classes.
I found this issue when tinkering with cross-inheritance in cppyy.
It looks like upstream cppyy also faces a similar problem. Opened a PR stating the issue at https://github.com/wlav/cppyy/issues/280.
> Does not contribute to test cases that pass in cppyy.
Added in tests with multi-level and multiple inheritance.
> fix `GetVariableOffset` in cases of multi-level and multiple inheritance

- Emscripten-build-instructions.md
This PR will add instructions on how to build a wasm version of CppInterOp and xeus-cpp.
> Add Emscripten Build Instructions

- unittests/.clang-tidy
disable unnecessery clang-tidy checks in unittests
> disable unnecessery clang-tidy checks in unittests

- .github/workflows/ci.yml
- .github/workflows/clang-tidy-review.yml
- .github/workflows/deploy-pages.yml
- Emscripten-build-instructions.md
- README.md
- docs/DevelopersDocumentation.rst
- docs/InstallationAndUsage.rst
- docs/conf.py
> Documentation changes as REPL is set to ON by default

- README.md
This PR removes badge which referenced the old ci.yml file (this has been replaced in https://github.com/compiler-research/CppInterOp/pull/402 already and just needs removing)
> Remove duplicate badge which was not removed in previous PR.

- .github/workflows/Windows.yml
- .github/workflows/non-emscripten.yml
- README.md
This PR will separate out the Windows jobs from the Ubuntu and MacOS jobs in the non emscripten ci, to allow it be easier maintained and updated.
> Separate out Unix and Windows non emscripten builds ci

- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/TestSharedLib/CMakeLists.txt
- unittests/CppInterOp/TestSharedLib/TestSharedLib.h
Fixes issues with how the DLM tests are built in ROOT, and forces the symbol to be exported in Release mode
> Fix issues with DLM tests

- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu.yml
- README.md
This PR will separate out Ubuntu and MacOS builds ci, making them easier to maintain and update. After this we will have badges for Ubuntu and MacOS builds separate in the README.md .
> Separate out Ubuntu and MacOS builds ci

- Emscripten-build-instructions.md
This updates the emscripten build instruction to match the PR in xeus-cpp https://github.com/compiler-research/xeus-cpp/pull/199
> Update Emscripten-build-instructions.md to match PR in xeus-cpp https://github.com/compiler-research/xeus-cpp/pull/199

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- patches/llvm/emscripten-clang19-2-shift-temporary-files-to-tmp-dir.patch
This changes the ci which builds the emscripten version of xeus-cpp to match the PR in https://github.com/compiler-research/xeus-cpp/pull/199/files
> Fix xeus cpp build

- .github/workflows/deploy-pages.yml
- Emscripten-build-instructions.md
See https://github.com/compiler-research/xeus-cpp/pull/200
> Fix copying xcpp.data for xeus-cpp-lite deploy page

- .github/workflows/emscripten.yml
This PR will make the llvm build options match the emscripten forge recipe
> Make llvm build options match emscripten forge recipe

- .clang-tidy
- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
Resolving unary operators and operators defined within namespaces.
Required for `+` op in `std::string`.
Three issues at cppyy. Requires a patch for both CPyCppyy and cppyy-backend.
I have added in tests cases for unary operator lookup and lookup of operator within a namespace.
> Update `GetBinaryOperator` to `GetOperator`

- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu.yml
My local testing on an osx arm Macbook found an 35% reduction in the size of the build folder when using Ninja to build llvm. This should help reduce the pressure on the cache. Supposedly Ninja is faster so we should see a speed in the llvm build when we have to rebuild the cache. If the ci passes then all Ubuntu and MacOS builds should be cleared from the cache before merging.
> Use Ninja to build llvm in the ci (osx and Ubuntu)

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- lib/Interpreter/CMakeLists.txt
This PR should fix the emscripten build in the ci. The new llvm options may not be necessary. They are just used in emscripten-forge so I decided to add here for consistency. The LDFLAGS definitions are needed otherwise the CppInterOp shared library is not built correctly. I have cleared the cache of one build to check I have not broken the build there. Once it passes this PR should be ready for merging.
> Add correct options to build xeus-cpp-lite deployment correctly

- Emscripten-build-instructions.md
This fixes the wasm build instructions. It matches what is done in https://github.com/compiler-research/CppInterOp/pull/420
> Fix emscripten build instructions

- .github/workflows/deploy-pages.yml
There is a known bug in Jupyter Lite where is jupyter_server is not installed then the contents flag doesn't work to upload files (see https://github.com/jupyterlite/jupyterlite/issues/1453). This PR adds this dependency to fix that so we can upload the example notebook (not everything in the notebook works).
> Add example notebooks to deployment

- .github/workflows/Windows.yml
Recently Github made Windows 2025 runners available. This updates the ci to use them.
> Upgrade Windows ci runners to Windows 2025

- .github/workflows/Windows.yml
I made a mistake in https://github.com/compiler-research/CppInterOp/pull/429 and forget to update all the Windows jobs to 2025. This didn't show up until it was merged into main.  This PR will fix that. Once the PR passes in this PR I will merge to fix the broken main branch Windows ci.
> Fix Windows 2025 ci

- .github/workflows/deploy-pages.yml
The MacOS 15 runner is around 5 minutes faster than the Ubuntu one at emscripten builds, so switching the runner we use to MacOS so we get faster new deployments.
> Switch deploy runner to MacOS

- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
These `_s` secure functions are introduced in C11 as optional bounds-checking interfaces, there is no guarantee that they are implemented/enabled by other compilers.
> Restrict the use of `_s` (Annex K) functions to MSVC

- Emscripten-build-instructions.md
Thie PR updates Emscripten-build-instructions.md to include instructions so user can add own notebooks to own deployments
> Add instructions so users can add notebooks to Jupyter lite deployments

- .github/workflows/emscripten.yml
When doing the emscripten llvm build in the ci we have a random valgrind install as a dependency. This can be removed.
> Remove valgrind install emscripten.yml

- CMakeLists.txt
Currently we get a warning when configuring CppInterOp that we should define the project before using enable language. This PR should fix this issue. See here for the warning this PR should remove https://github.com/compiler-research/CppInterOp/actions/runs/12732612570/job/35488024303#step:10:76
> Move enable language in cmakelist.txt to avoid configure warning

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
Our emscripten build workflows clone the whole of the xeus-cpp history when all we need is the latest commit. This workflow changes it to a shallow clone of xeus-cpp (may  provide a small speed increase)
> Shallow clone xeus cpp emscripten build

- .github/workflows/MacOS.yml
MacOS will never support CUDA gpus so no need to have it as a target to build when building llvm on MacOS.
> Remove NVPTX llvm targets to build MacOS.yml

- .github/workflows/emscripten.yml
emsdk supports Ninja builds, so this PR switches the ci over the Ninja for hopefully smaller and faster emscripten llvm builds. I have cleared the cache of emscripten llvm builds to check I haven't broken anything. Once the ci passes this PR should be ok to merge.
> Use Ninja for emscripten build of llvm

- .github/workflows/deploy-pages.yml
This PR should fix the warning we are currently getting when we build pur deployment about not having linarchive c
> Install libarchive-c to remove warning when building jupyter lite deployment

- .github/workflows/deploy-pages.yml
A better alternative to the jupyter_server module we use is to use what the main jupyter lite demo has as core modules https://github.com/jupyterlite/demo/blob/0cddee229c47161aadc17e836ca0b78f991a7908/requirements.txt#L2
> Change from jupyter_server to jupyterlite-core jupyterlab

- docs/Emscripten-build-instructions.rst
- docs/index.rst
Currently we only have the emscripten build instructions in a markdown file in the repo. This adds the documentation to CppInterOps online documentation.
> Add emscripten build instructions to online documentation

- lib/Interpreter/Compatibility.h
@alexander-penev  We ran into an issue with torchlib that is triggered by the loading of `std::regex`. I have replaced the usage with `llvm::Regex` that fi xes it. Can you verify if this works with your usecases when developing the feature? The unittests for codecomplete pass but I am not sure if it is extensive enough.
.
> Replace std::regex in codecomplete to use llvm::regex

- .github/workflows/Ubuntu.yml
- .gitignore
- unittests/CppInterOp/CMakeLists.txt
> Improve unittest cmake and gitignore

- CMakeLists.txt
Fixes issues building libCling and unit tests on ROOT for winx86
> [cmake] Perform symbol exports depending on winx86 and winx64

- .github/workflows/emscripten.yml
- CMakeLists.txt
- lib/Interpreter/CMakeLists.txt
- patches/llvm/emscripten-clang19-3-remove-zdefs.patch
When building the emscripten version of CppInterOp we get undefined linker flag soname and undefined z value warning here https://github.com/compiler-research/CppInterOp/actions/runs/12736895837/job/35497425197#step:9:213 . This PR should fix this.
> Remove soname and zdefs flags emscripten build

- .github/workflows/Ubuntu.yml
- .github/workflows/emscripten.yml
The Ubuntu arm runners finally became generally available. This PR adds them to our ci.
> Add ubuntu 22.04 arm runners

- .github/workflows/deploy-pages.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
This PR fixes our Jupyter Lite deployment.
> Fix deployment due to new jupyter lite xeus

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
Implements `DemangleSymbol` and `IsClassPolymorphic` APIs. These are needed to implement [`Cppyy::GetActualClass`](https://github.com/compiler-research/cppyy-backend/blob/5025eda5db4fafc6811b0d1f4c8f75dbe726f00b/clingwrapper/src/clingwrapper.cxx#L655).
Fixes 8 tests on cppyy, once `Cppyy::GetActualClass` is implemented.
Implemented necessary tests.
> Implement `Demangle` and `IsClassPolymorphic` APIs

- lib/Interpreter/Compatibility.h
- unittests/CMakeLists.txt
- unittests/CppInterOp/ScopeReflectionTest.cpp
Set of patches required on top of InterOp master for enabling ROOT, which can added upstream.
> Minor patches to unittests, improve offset initialization in getExecutionEngine

- .github/workflows/emscripten.yml
Our cache for our emscripten llvm builds is quite large. This is the first in a series of 2 PRs to reduce its impact on our total cache. This should provide a small speed up in our emscripten builds, since the emscripten llvm uploads and downloads should be quicker.
> Reduce emscripten cache size by removing everything but llvm, clang and build folders

- .github/workflows/emscripten.yml
This PR reduces the emscripten cache size further by removing unneeded llvm and clang folders after build is done
> Reduce emscripten cache size further by removing unneeded llvm and clang folders after build is done

- .github/workflows/MacOS.yml
Not entirely sure whether this will work. I think in the ci we can replace the clang-repl target with clangInterpreter clangStaticAnalyzerCore and still pass. This might have a small effect on the cache size it produces. Need to wait for the ci to run to see if this is the case.
> Reduce MacOS llvm cache

- .github/workflows/MacOS.yml
For some reason the Nvidia target is needed for cling based osx jobs. No idea why.
> Add back CUDA target to MacOS cling jobs

- .github/workflows/MacOS.yml
I rushed this PR https://github.com/compiler-research/CppInterOp/pull/466 and messed it up. This PR moves NVPTX to the correct place
> Fix previous commit and move nvptx to targets to builds macos cling builds

- .github/workflows/Windows.yml
Just like what was done in https://github.com/compiler-research/CppInterOp/pull/465 , by only building clangInterpreter clangStaticAnalyzerCore instead of clang-repl then we should see a small decrease in the build size while still passing all tests. Given we have a large number of ci jobs, all these small reductions will build up.
> Reduce Windows cache size by only building necessary targets

- .github/workflows/Windows.yml
We are unlikely to ever have Windows builds passing all tests building against llvm 17 and 18. After https://github.com/compiler-research/CppInterOp/pull/463 is merged this PR should be merged, so we can remove the cache used up by these jobs. Keeping the llvm 19 build makes sure our Windows build doesn't break. With the freed up cache space I plan to replace these 2 Windows jobs with Ubuntu 24.04 x86 coverage, which is a good trade.
> Remove Windows llvm 17 and 18 jobs from ci

- .github/workflows/Ubuntu.yml
This PR reduces the llvm cache size on Ubuntu by only bulding clangInterpreter clangStaticAnalyzerCore instead of clang-repl.
> Reduce Ubuntu cache size by only building necessary targets

- .github/workflows/emscripten.yml
Just like I have done with the non wasm builds I have changed the clang-repl target to be exactly what we need (i.e. clangInterpreter clangStaticAnalyzerCore). This will speed up the emscripten llvm build, and reduce the cache size.
> Use clangInterpreter clangStaticAnalyzerCore instead of clang-repl target to reduce emscripten llvm cache size

- .github/workflows/Ubuntu.yml
By turning benchmarks, examples and tests off we don't carry these folders over to our build folder. This will have the effect of decreasing the size of the cache for Ubuntu. Just doing it for the clang-repl jobs for this PR to limit the effect of any PRs which may go in while the CI finishes on this PR.
> Reduce Ubuntu cache size by not including benchmarks, examples and tests

- .github/workflows/Ubuntu.yml
My local build suggests we do not need these files after the llvm build is complete. They add up to a significant size, so if the ci passes, then it should lead to a significant reduction in the llvm cache taken up by Ubuntu jobs. Next i'll move onto doing this for MacOS jobs if it works.
> Remove unneeded built tools and compile_commands.json build.ninja Ubuntu ci

- .github/workflows/emscripten.yml
This PR removes the x86 osx emscripten job from the ci, and the Ubuntu 22.04 x86 and arm ones. This keeps us covered for emscripten job for Linux and osx platforms, but only keeps the fast Github runners.
> Remove osx x86 job and Ubuntu 22 emscripten jobs from ci

- .github/workflows/Ubuntu-arm.yml
- README.md
This splits the Ubuntu workflow into one for x86 and one for arm. This makes it easier to maintain, and allows us to have a build badge for both build targets.
> Split Ubuntu workflow into one for x86 and one for arm

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- README.md
This splits the MacOS workflow into one for x86 and one for arm. This makes it easier to maintain, and allows us to have a build badge for both build targets.
> Split macos workflow into x86 and arm

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
This build changes from using the cling target to clinginterpreter in the ci to save space in the cache.
> Change cling to clingInterpreter target macos ci

- .github/workflows/Ubuntu-arm.yml
Now that support for Ubuntu 22.04 arm has been added to cppyy we can turn it on in the CppInterop Ubuntu-arm.yml workflow.
> Turn on Ubuntu 22.04 arm cppyy jobs

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
- environment-wasm.yml
This is a PR to upgrade the emsdk version we use to version 3.1.73, once emscripten forge is finished with its transition to this version.
> Upgrade to emsdk to version 3.1.73

- .github/workflows/clang-format.yml
- lib/Interpreter/Compatibility.h
The clang format workflow is broken because it tries to get a git-clang-format by wgetting it. Git-clang-format is not used as far as I can tell from the workflow, so should be safe to just remove the 'Download git-clang-format' section of the workflow.
> Fix clang-format workflow

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
Resolve all `EnumConstantDecl`s declared in a class.
1 test at cppyy.
Implemented tests.
> Add `GetEnumConstantDatamembers` function

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
Implements  `IsFunctionPointerType` function
> Add `IsFunctionPointerType` function

- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
Fixes code generation of `MakeFunctionCallable` for the cases where the return type of the function is a function pointer.
Potentially fix 4 tests at cppyy.
Implemented a test case where it used to fail, but passed with these changes.
> fix `MakeFunctionCallable`'s codegen when return type is a function pointer

- CMakeLists.txt
There is a bug in the CMake where
`option(CPPINTEROP_ENABLE_TESTING "Enables the testing infrastructure." BOOL)`
is conditional and for non-Emscripten builds the default is explicitly set to ON. This is incorrect and does not allow users to override the option, leading to testing always being on.
The `option` keyword must be defined once with one default, which CMake then overrides from the user's command line option
> fix bug in CMake preventing user from disabling testing

- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
Fixes code generation of `MakeFunctionCallable` for templated operators.
Look at the inline comment.
Fixes one test case in cppyy.
Tests included.
> fix `MakeFunctionCallable`'s codegen for templated operators

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
Add `IsPointerType`, `GetPointerType`, `IsReferenceType` & `GetNonReferenceType` functions
Helps fix issues in cppyy.
Tests included.
> Add Is/Get Pointer & Reference functions

- include/clang-c/CXCppInterOp.h
- lib/Interpreter/CMakeLists.txt
Add the missing `CINDEX_LINKAGE` macros for C APIs
> Fix symbol visibility issues for C API

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
Resolve and instantiate (if templated) overload from vector of overloads for the given template parameter types and argument types.
With these changes, we replicate clang's overload resolution and template instantiation.
Fixes 10 test cases in cppyy.
Can close https://github.com/compiler-research/CppInterOp/pull/352 and https://github.com/compiler-research/CppInterOp/pull/511.
Included tests
> Add `BestOverloadFunctionMatch` & `IsFunction` Remove `BestTemplateFunctionMatch`

- CMakeLists.txt
This PR includes a set of changes fixing bugs in the CMake:
Move interpreter and testing options outside the standalone build condition: The options are not correctly propagated (or defined) and CppInterOp does not configure or check the flags when it is not built standalone. This has more fatal consequences, currently in a non-standalone built like in ROOT you can set both `USE_CLING` and `USE_REPL` ON. This sets both definitions and include directories, since the check only happens inside the standalone block.
Improve the check when both interpreter modes are OFF: When having both modes ON, I noticed the style of [CMakeLists.txt#L296-L305](https://github.com/compiler-research/CppInterOp/blob/7caf10b1ccae74e62600b1b5fe05dc4e71db93bb/CMakeLists.txt#L296-L305 ) is not optimal and can be …
> [cmake] Fix bugs if CppInterOp is a non-standalone build

- CMakeLists.txt
This PR drops messages that seem like they are used for debugging, making the build less verbose.
Closes #520
> [cmake] Drop unecessary Cling and LLVM path messages

- lib/Interpreter/CMakeLists.txt
- unittests/CppInterOp/TestSharedLib/CMakeLists.txt
CppInterOp used to use `target_link_options`  before #483 went in. Not sure why this change was made. set_target_properties comes under the old style cmake and `target_link_options` and `target_compile_options` falls under mordern cmake which cmake promotes to be used with `target_link_libraries`.
This PR reverts back to what we were originally using. `add_llvm_library` internally make use of target_link_libraries and we should use `target_link_options` that goes with it .
> Use target_link_options instead of set_target_properties for linking

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
Given we need to install CppInterOp as part of the xeus-cpp-lite build process we don't really need to reference CPPINTEROP_BUILD_DIR anymore, since it will be found in the PREFIX folder.
> Remove references to CPPINTEROP_BUILD_DIR in Emscripten build

- unittests/CppInterOp/CMakeLists.txt
I believe this reference to LLVM_LINK_COMPONENTS in the unittests folder is unused. 
> Remove unused LLVM_LINK_COMPONENTS unittests folder

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
Clang.js takes a while to build. We don't use clang.js, we just use the library. In theory we should be able to pass all Emscripten tests by building the libclang target instead of clang target. This will reduce the Emscripten cache (freeing up some very much needed space in the Github cache with the llvm 20 upgrade PR to come), and will speed up build times for developers. If the ci passes, then I will update the documentation accordingly. 
> Reduce the Emscripten build size and reduce build time by building libclang target instead of the clang target

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
Just like https://github.com/compiler-research/CppInterOp/pull/531 did for the clang target, this PR swaps out the lld target for the lldWasm target, speeding up the Emscripten llvm build time, and reducing the size the build takes up in the cache.
> Change lld target to lldWasm target Emscripten build

- environment-wasm.yml
Once this PR in xeus-cpp https://github.com/compiler-research/xeus-cpp/pull/277 is ready and merged, doctest will need to be added Emscripten conda environment in CppInterOp. 
> Add doctest to Emscripten conda environment

- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/CXCppInterOp.cpp
- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
as per https://github.com/compiler-research/CppInterOp/pull/440#issuecomment-2585773954
> Improve the test coverage of the C API

- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/exports.ld
patch for https://github.com/compiler-research/CppInterOp/pull/447#discussion_r2009932702
> Use `exports.ld` to export symbols

- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CXCppInterOp.cpp
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/CppInterOpInterpreter.h
- unittests/CppInterOp/FunctionReflectionTest.cpp
Added ```Undo``` command for Clang-REPL. Reverts the last N operations performed by the interpreter.
1. Tests in ```unittests/CppInterOp/FunctionReflectionTest.cpp```.
2. Demo - https://res.cloudinary.com/abhi9av/video/upload/v1740997292/wqgfbgqefrwpx2o7ko95.mp4
> Added undo command for CppInterOp

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
This PR makes general improvements to Emscripten build and ci
- Reduces the size of the Emscripten cache by removing NATIVE tools folder
- If developer decided to build all targets, then they get a reduced number of targets that are not relevant (new options inspired by https://github.com/emscripten-core/emsdk/blob/b665079cb9ad9eb1704652f962281a7fa1633e2d/emsdk.py#L1124C42-L1124C66 in emsdk and https://github.com/WebAssembly/wasi-sdk/blob/d94a133384eb7a805ad7185195db96435d2ecdac/cmake/wasi-sdk-toolchain.cmake#L86 in wasi sdk)
- Ninja defaults to a larger number of parallel processes than the number of cpu cores. This means we currently build slower using Ninja than it is capable of
- We do not need to set the …
> General improvements to Emscripten build and ci

- .github/workflows/deploy-pages.yml
https://github.com/compiler-research/CppInterOp/pull/533 should have had changes to the deployment workflow. Only thought about it once the PR was merged. This PR makes the required changes. 
> Fix deploy workflow changes which should have gone in https://github.com/compiler-research/CppInterOp/pull/533

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows.yml
- .github/workflows/clang-tidy-review.yml
- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- .github/workflows/markdown-linter.yml
- CMakeLists.txt
- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/CMakeLists.txt
- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
- unittests/CMakeLists.txt
- unittests/CppInterOp/EnumReflectionTest.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
This PR removes trailing whitespace in workflow yml files. This fixes one of the issues needed to have a yaml file linter check any workflow file changes in the future. Currently such a workflow would not pass.
I've also used this PR to remove the trailing whitespaces in the source files, test files and cmakelists.txt files 
> [ci] Remove trailing whitespace in workflow yml files, source files, test files and cmakelists.txt files

- lib/Interpreter/exports.ld
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/InterpreterTest.cpp
Hey @vgvassilev, 
If you remember, we were discussing the changes needed to handle the LLVMargs from FrontendOpts for clang-repl the other day.
This led to me coming up with this PR on llvm https://github.com/llvm/llvm-project/pull/132670
But I think CppInterOp does take some inspiration from the above in the past and has added a block for handling the LLVM args
https://github.com/compiler-research/CppInterOp/blob/e1ace5198a7a89109526820b88a427deee087630/lib/Interpreter/CppInterOp.cpp#L2962-L2975
Hence we should be able to process any exception handling case for our emscripten build through cppinterop (though clang-repl in the browser itself won't be able to handle these) 
This adds a simple test case for the same. Which we can possibly remove along with the above code block .... once …
> Add test for verifying exception handling for emscripten builds

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
Now that the Emscripten build of xeus-cpp builds tests, we can now run them as part of the Emscripten workflow in CppInterOp. This allows us to ensure that any changes to Emscripten build/functionality of CppInterOp doesn't break the Emscripten build/functionality of xeus-cpp.
> Run xeus-cpp-lite tests Emscripten workflows

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows.yml
Currently we are have just enough room in the cache to include the native builds of llvm 20 (see image below). My plan was to remove the llvm 19 Windows job to make room for the Emscripten llvm 20, but that won't be enough given we are so close to capacity. This PR should reduce the impact of the cling llvm builds enough that we have enough room for the Emscripten builds. I'll be able to quantify the impact of this PR once the workflows finish running.
> Reduce cling llvm cache (makes room for Emscripten llvm 20 builds)

- lib/Interpreter/CppInterOpInterpreter.h
The `clang::Interpreter` wrapper previously returned a pointer to const, but the actual `clang::Interpreter` did not. This breaks code for anyone porting from `clang::Interpreter` to `Cpp::Interpreter`, especially since most operations on the execution engine are mutations of some sort.
Yes, the user could static cast the wrapper to the inner interpreter, but, at that point, why both exposing the `getExecutionEngine` function at all?
> Return pointer to non-const for getExecutionEngine

- cmake/modules/GoogleTest.cmake
This PR simply updates the GoogleTest we are using to 1.16.0 released 2 months ago. Hopefully the ci passes first time, but this wasn't true of the update to 1.15.2 . 
> Update GoogleTest used to 1.16.0

- .github/workflows/clang-tidy-review-post.yml
- .github/workflows/clang-tidy-review.yml
This PR updates ZedThree/clang-tidy-review to version 0.21.0 due this issue in version 0.20.1 https://github.com/ZedThree/clang-tidy-review/issues/144
I've put the same PR in xeus-cpp here https://github.com/compiler-research/xeus-cpp/pull/284
> Update ZedThree/clang-tidy-review to version 0.21.0

- lib/Interpreter/CXCppInterOp.cpp
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/CppInterOpInterpreter.h
- unittests/CppInterOp/CUDATest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
@Vipul-Cariappa and I were discussing a use case yesterday (especially while building with repl) and this is what we realized
1) The function responsible for creating `clang::Interpreter` is `createClangInterpreter` which can return a nullptr, for eg 
https://github.com/compiler-research/CppInterOp/blob/c3384fb9d784a3f1606b6fc20c283c1e48d9b14b/lib/Interpreter/Compatibility.h#L277
2) This is assigned to `inner` while the constructor for `compat::Interpreter` is called
https://github.com/compiler-research/CppInterOp/blob/c3384fb9d784a3f1606b6fc20c283c1e48d9b14b/lib/Interpreter/CppInterOpInterpreter.h#L153
which means `inner` can be `nullptr`
3) And then if we look at `CreateInterpreter` from the top, we're creating the `compat::Interpreter` here …
> Add error propagation to interpreter creation logic

- unittests/CppInterOp/CMakeLists.txt
While looking at https://github.com/compiler-research/CppInterOp/actions/runs/14514284970/job/40723447067?pr=491 I noticed that the cuda tests are being run twice, due to EXTRA_TEST_SOURCE_FILES not being reset between setup for the 2 sets of tests. This PR should fix the issue. It only should be reset for the native build, because main.cpp is needed in both test runs for the Emscripten build.
> Stop cuda tests being run twice

- environment-wasm.yml
The latest release of xeus got released, and requires nlohmann_json to be 3.12.0 . Until this PR is in the ci will fail
(see https://github.com/compiler-research/xeus-cpp/actions/runs/14604191183/job/40969335106#step:5:97).
> Pin nlohmann_json to 3.12.0

- cmake/modules/GoogleTest.cmake
Googletests most recent version 1.17.0 got released a few days ago. Unlike previous versions they have made the minimum required c++ standard c++17 for this version. As we don't use the googletest that comes with CppInterOp for the cling 1.0 job, we should be able to upgrade to this new version.
> Update GoogleTest used to 1.17.0

- CMakeLists.txt
- CONTRIBUTING.md
- cmake/modules/GoogleTest.cmake
- docs/doxygen.cfg.in
- docs/doxygen.css
- include/clang/Interpreter/CppInterOp.h
- lib/Interpreter/Compatibility.h
- lib/Interpreter/CppInterOp.cpp
- lib/Interpreter/CppInterOpInterpreter.h
- lib/Interpreter/DynamicLibraryManager.cpp
- lib/Interpreter/DynamicLibraryManager.h
- lib/Interpreter/DynamicLibraryManagerSymbol.cpp
- lib/Interpreter/Paths.cpp
- lib/Interpreter/Paths.h
- unittests/CppInterOp/CMakeLists.txt
There was many typos in CppInterOp including in the names of variables and functions in the code. This PR fixes these typos.
A similar PR fixing typos in xeus-cpp is here https://github.com/compiler-research/xeus-cpp/pull/285
> Fix typos in repo

- docs/Emscripten-build-instructions.rst
We currently only talk about the Jupyter Lite deployment in the readme file. This makes the deployment more visible
by adding a link in the main page of CppInterOp read the docs page. This has already been done in the xeus-cpp repo here https://github.com/compiler-research/xeus-cpp/pull/275
> Mention Emscripten xeus-cpp deployment in read the docs documentation

- .github/workflows/Ubuntu-arm.yml
The coverage job appears has dissapeared from our ci. No idea when this happened. This PR should fix it.
> Add coverage job back to ci

- unittests/CppInterOp/FunctionReflectionTest.cpp
We may need to find a way to catch this.
> Fix a typo in the `TOperator` test

- lib/Interpreter/CppInterOpInterpreter.h
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/DynamicLibraryManagerTest.cpp
Now that https://github.com/llvm/llvm-project/pull/133037 has been merged, we should be able to test out loading shared libraries for the emscripten build.
> Frame tests for loading shared objects for the emscripten build

- lib/Interpreter/CppInterOp.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
`GetOperator` now resolves the operator into the base classes. 
Helps with smart pointers. Fixing 9 tests in cppyy.
Tests included.
> fix operator resolution to check base classes

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows-arm.yml
- .github/workflows/Windows.yml
- .github/workflows/emscripten.yml
- patches/llvm/cling1.2-LookupHelper.patch
- unittests/CppInterOp/DynamicLibraryManagerTest.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
This PR makes CppInterOp compatible with cling 1.2, and jobs the cling 1.0 jobs. I will remove cling 1.0 support from CppInterOp in a separate PR soon.
> Add cling 1.2 support

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
- unittests/CMakeLists.txt
- unittests/CppInterOp/CMakeLists.txt
This PR adds the ability to run the Emscripten tests in a browser. This partially contributes to the goal of https://github.com/compiler-research/CppInterOp/issues/500 , which is to run a c++ tutorial html file utilising CppInterOp, as part of automated testing.
> Run Emscripten tests in a browser

- lib/Interpreter/Compatibility.h
This patch drops pointer arithmetic used to obtain the `llvm::orc::LLJIT` from older Cling versions. This would make for safer usage of the `cling::Interpreter` and good to have for the 1.7.0 stable release that ROOT will move to.
> [interpreter] Drop IncrementalExecutor offsets to obtain LLJIT for Cling

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
This PR will be used to check if the fix proposed in https://github.com/compiler-research/xeus-cpp/pull/312 will work in fixing the error in CppInterOps Emscripten workflows. Once this xeus-cpp PR is in, I will revert my change which points towards the fork of Compiler Researchs xeus-cpp. 
> Fix Emscripten workflows

- .github/actions/Build_and_Test_CppInterOp/action.yml
This PR removes redundant build of Google Test in Windows ci (built as part of check-cppinterop)
> Remove redundant build of Google Test in Windows ci (built as part of check-cppinterop)

- include/CppInterOp/CppInterOp.h
- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
> add `IsLValueReferenceType` & `GetReferencedType`

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows-arm.yml
- .github/workflows/Windows.yml
- README.md
- docs/DevelopersDocumentation.rst
- docs/InstallationAndUsage.rst
This PR remove LLVM_ENABLE_ZSTD=OFF ,LLVM_ENABLE_TERMINFO=OFF and LLVM_ENABLE_LIBXML2=OFF  options llvm native build. These options were added when CppInterOp was trying to combine the Emscripten and native llvm builds into 1.
> Remove LLVM_ENABLE_ZSTD=OFF, LLVM_ENABLE_TERMINFO=OFF and LLVM_ENABLE_LIBXML2=OFF  options llvm native build

- include/CppInterOp/CppInterOp.h
- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/InterpreterTest.cpp
This patch offers an API to switch back and forth different interpreters which can come at handy in several occasions including research into implementing threading.
Fixes #302.
> Stack the created interpreters.

- include/clang/Interpreter/CppInterOp.h
While investigating how to get a Windows build of cppyy here https://github.com/compiler-research/CppInterOp/pull/605 I found that the deprecation message is not understood by the MSVC compiler. Without this fix anything built on top of CppInterOp on Windows using the MSVC compiler will not work.
> Use pragma for deprecated warning message MSVC compiler

- lib/CppInterOp/CppInterOp.cpp
This should fix a longstanding issue with resource deallocation in CppInterOp.
> Destroy the interpreters when they are owned.

- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
We are currently getting the following warning message in the coverage workflow. It seems the file key in codecov has changes to files in a newer version. This PR fixes that, and should no longer have this warning.
> Update codecov action to use files instead of file

- .readthedocs.yaml
- docs/conf.py
Currently the link to the CppInterOp API documentation on readthedocs doesn't work (see https://cppinterop.readthedocs.io/en/latest/build/html/index.html ). The rest of the documentation work (see https://cppinterop.readthedocs.io/en/latest/ ) . The objective of this PR is to get the API documentation working again.
> Fix api documentation readthedocs

- .github/workflows/MacOS-arm.yml
- .github/workflows/MacOS.yml
- .github/workflows/Ubuntu-arm.yml
- .github/workflows/Ubuntu.yml
- .github/workflows/Windows-arm.yml
- .github/workflows/Windows.yml
- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
This PR should fix the issue of actions appearing as paths instead of names on the Github UI
The interpreter mode is now dynamically inserted (Cling/Clang-REPL)  based on the config
before:
after:
> [ci] fix workflow names

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
> Update Emscripten instructions to match xeus-cpp in where dependencies are installed from + mount tag files (no longer preloaded in xeus-cpp)

- include/CppInterOp/CppInterOp.h
- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
> Add `GetPointerType` & update `GetReferencedType` for rvalue

- include/CppInterOp/CppInterOp.h
- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/TypeReflectionTest.cpp
> add `GetSpellingFromOperator` & `GetOperatorFromSpelling`

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
This is the case where the instantiated function is present in one of the libraries loaded or the host application.
Fixes a test in cppyy.
Tests included.
> fix: codegen need not instantiate func body if it can be resolved

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
Enables `func(std::move(args))` when `func` is templated.
Fixes a test in cppy.
Included
> fix codegen & instantiation of templated function with rvalue as parameter

- lib/CppInterOp/CppInterOp.cpp
This prevents conflicts with ROOT that also uses `cf`, allowing us to integrate JitCall incrementally and co-exist with CallFunc
> rename generic/ctor wrapper name

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
adapted from cling
Fixes 2 issues in cppyy.
Included.
> fix: codegen for templates with multiple parameter packs

- .github/workflows/emscripten.yml
- .github/workflows/main.yml
Fixes https://github.com/compiler-research/CppInterOp/issues/597
> Only cancel in progress workflow runs for pull requests

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
- lib/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
CppInterOps Emscripten library can now be compiled to a static library, and pass almost all the same tests as the shared library build. This PR adds what is necessary to build the Emscripten static library, and run the tests on this build.
> Add Emscripten static library build CppInterOp

- .clang-format
Since cling 1.0 support got dropped the minimum c++ standard supported by CppInterOp was c++17 . Therefore this PR updates the clang-format standard CppInterOp is using to c++17. This a valid value and was taken from xeus-cpp (see https://github.com/compiler-research/xeus-cpp/blob/7a3a24bbbdcc82f8626b71ed7a3028a637923ce3/.clang-format#L76C11-L76C16)
> Update clang-format standard to c++17

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/ScopeReflectionTest.cpp
Helps fix up to 5 tests in cppyy.
> Fix bugs related to printing types

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
> Run browser tests on Windows

- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
Without this change, the documentation tag won't work when build locally.
> Fix Jupyter Lite serve instruction

- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
- patches/llvm/emscripten-clang20-3-enable_exception_handling.patch
CppInterOps xeus-cpp deployment doesn't have exception handling working due to this patch being missing from the llvm build. This patch was taken from Emscripten forge here https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/patches/enable_exception_handling.patch . I have tested this patch locally to check it fixes the deployment.
> Enable exceptions deployment

- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
This PR makes it so the SIMD Acceleration through WebAssembly Intrinsics example works if you follow the Emscripten build instructions
> Fix XEUS_CPP_RESOURCE_DIR in Emscripten build instructions

- .github/workflows/deploy-pages.yml
- .github/workflows/emscripten.yml
- Emscripten-build-instructions.md
- docs/Emscripten-build-instructions.rst
- scripts/browser_tests_safari.py
- unittests/CppInterOp/CMakeLists.txt
> Run browser tests in safari

- .github/workflows/emscripten.yml
- patches/llvm/emscripten-clang19-4-enable_exception_handling.patch
This PR backports the enable exception handling patch to llvm 19, and according to my local testing will allow the failing test in https://github.com/compiler-research/CppInterOp/pull/678 to pass, so that the emscripten workflow will go green. For this to work, you would need to clear the cache on main of Emscripten llvm 19 builds, merge this in, and once the workflow on main has rebuilt the cache, rebase that PR.
> Backport enable exception handling patch to llvm 19

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/VariableReflectionTest.cpp
This is a bug report.
```c++
template <typename T>
struct ClassWithStatic {
static T const ref_value;
};
template <typename T>
T constexpr ClassWithStatic<T>::ref_value = 42;
ClassWithStatic<int> x;
```
```c++
Cpp::GetVariableOffset(x.ref_val); // FAILS
```
---
Will help fix a test in cppyy.
> fix GetVariableOffset for templated static variable

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
> fix JitCall codegen for duplicate symbols within namespaces

- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
> fix JitCall codegen for function with lambda as return value

- lib/CppInterOp/Compatibility.h
- lib/CppInterOp/CppInterOp.cpp
- unittests/CppInterOp/InterpreterTest.cpp
MakeResourceDir is in the compatibility header file despite the fact it is not dependent on what llvm version you are using, or whether you are using cling or clang-repl. Therefore this PR removes is, and just replaces the function in the code.
> Remove unneeded MakeResourceDir

- CMakeLists.txt
This avoids resetting compiler flags that the surrounding project already took care of.
Tested when built inside ROOT, needed to fix the AddressSanitizer build (avoid resetting `-z undefs` when building shared libraries for testing).
> Only include `AddLLVM` / `HandleLLVMOptions` when standalone

- docs/DevelopersDocumentation.rst
- include/CppInterOp/CppInterOp.h
- lib/CppInterOp/CppInterOp.cpp
- lib/CppInterOp/CppInterOpInterpreter.h
- unittests/CppInterOp/CMakeLists.txt
- unittests/CppInterOp/DynamicLibraryManagerTest.cpp
- unittests/CppInterOp/FunctionReflectionTest.cpp
- unittests/CppInterOp/InterpreterTest.cpp
- unittests/CppInterOp/TestSharedLib2/CMakeLists.txt
- unittests/CppInterOp/TestSharedLib2/TestSharedLib.cpp
- unittests/CppInterOp/TestSharedLib2/TestSharedLib.h
- unittests/CppInterOp/VariableReflectionTest.cpp
Big changes in this PR. Some parts of the explanation might be like a conversation.
**Question:** Do we need a per-interpreter lock?
**Answer:** Yes. Ideally, that would improve the performance in multi-threaded cases.
**Question:** Does the InterOp API fully support dispatching queries (some kind of lookup) or compiling code across multiple interpreters at the same time?
**Answer:** Actually, (I guess) No. Our API only supports stack-like access of multiple interpreters.
_Example code that will not work:_
```c++
auto interpreter_1 = Cpp::CreateInterpreter();
Cpp::Compile(R"(
void f() {}
)");
auto f = Cpp::GetNamed("f");
auto interpreter_2 = Cpp::CreateInterpreter();
Cpp::Compile(R"(
void ff() {}
)");
auto ff = Cpp::GetNamed("ff");
auto f_callable = Cpp::MakeFunctionCallable(f); // This …
```
> [Thread-Safety] Add Mutex per Interpreter

- unittests/CppInterOp/FunctionReflectionTest.cpp
FunctionReflectionTest FailingTest1 is labelled as failing for an Emscripten shared library, but it passes when I enable it locally, so this PR removes the gtest_skip
> Enable FunctionReflectionTest FailingTest1 for Emscripten shared library

- .github/workflows/main.yml
The MacOS 13 x86 runners have just been deprecated (see https://github.com/actions/runner-images/issues/13046) and a MacOS 15 x86 runner has been created as a replacement (see https://github.com/actions/runner-images/issues/13045). This will be the final MacOS x86 Github runner.
> Move MacOS x86 runners to MacOS 15
