include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp
unittests/InterOp/ScopeReflectionTest.cpp
unittests/InterOp/TypeReflectionTest.cpp
unittests/InterOp/VariableReflectionTest.cpp

These functions are added to support templates in Executors

Fix templ execs

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp

This helps in debugging when inside cppyy-backend and using a debugger

Add func to call dump on TCppScope_t

---

lib/Interpreter/InterOp.cpp

Wrap printf in PRINT_DEBUG flag

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp

@vgvassilev this is a minimal reproducible example for the constructor not found error.

Force definition of special members

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/TypeReflectionTest.cpp

- This pull request will resolve issue #19 
-  I have implemented GetDimensions module and tested it successfully
-  Kindly review and let me know whether any further changes are required or not

Implemented GetDimensions module

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp
unittests/InterOp/ScopeReflectionTest.cpp

On running the test case it fails with the assert: 
```cpp
!hasUninstantiatedDefaultArg() && "Default argument is not yet instantiated!"
```
@vgvassilev can you please solve this?

Add test case on default args in templ class ctor

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/TypeReflectionTest.cpp

- This pull request will resolve issue #18 
- I have implemented IsSubType Module and ran it succesfully
- Kindly review it and please let me know whether any improvement or changes are required or not
- @vgvassilev and @sudo-panda

Implemented IsSubType Module Successfully

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp

- This pull request will resolve issue #15 
- I have implemented GetFunctionArgDefault module and implemented successfully
- Kindly review and let me know any further changes are required or not
- @vgvassilev and @sudo-panda

Implemented GetFunctionArgDefault Module 

---

lib/Interpreter/InterOp.cpp
unittests/InterOp/ScopeReflectionTest.cpp

Add test case for templated base classes

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp

- Fixes compiler-research/InterOp#13
- I have implemented and successfully tested IsConstant Module
- However there has been an unexpected hardware issue on my device so it has to be sent for servicing purpose, so it will be difficult for me to take up and resolve your issues/suggestions immediately
- Kindly review and pls let me know suggestions/improvements
- I would try to resolve and look over your suggestion as soon as possible 
- I am currently finding a way to continue being active and contribute

Implemented IsConstant Module

---

lib/Interpreter/InterOp.cpp
unittests/InterOp/ScopeReflectionTest.cpp

Fixes Base class not found error.

Add support for virtual bases in GetBaseClassOffset

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp

- Fixes #14 
- @vgvassilev and @sudo-panda 
- I have implemented and successfully tested GetFunctionArgName Module
- Kindly review and pls let me know any suggestions/improvements
- I would try to resolve/make changes as soon as possible

Implemented GetFunctionArgName Module

---

include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/TypeReflectionTest.cpp

Implement IsSmartPtrType.

---

.gitignore
include/clang/Interpreter/InterOp.h
lib/Interpreter/InterOp.cpp
unittests/InterOp/ScopeReflectionTest.cpp

Some trivial fixes are included as well.

Fix GetNamed not working for typedef'ed parents

---

README.md

Added simple description for new comers, technical advantages for experienced users.
> Not sure of the timeline of the CppInterOp features ported to Clang-REPL/ LLVM, so they have been referenced as upcoming features (described in future tense)
Request for Review: @vgvassilev

CppInterOp ReadMe content added

---

lib/Interpreter/InterOp.cpp
unittests/InterOp/FunctionReflectionTest.cpp

This patch should fix the valgrind issues.
cc: @sudo-panda

Properly implement placement new via InterOp::Construct.

---

.clang-format
.github/workflows/ci.yml
lib/Interpreter/InterOp.cpp

- This PR will add clang-format to the CI and fix #82 
- @vgvassilev and @sudo-panda pls review

Running clang-format on PR

---

.codecov.yml
.github/workflows/ci.yml

-Tried Adding Codecov setup, setup is being established however coverage report is not being generated hence issued a draft PR for your review @vgvassilev and @sudo-panda

Codecov setup

---

.github/workflows/ci.yml

Adding coverage variable in matrix so that codecov is triggered

Adding coverage variable for matrix

---

.clang-tidy
.github/workflows/ci.yml
.github/workflows/clang-tidy-review-post.yml
.github/workflows/clang-tidy-review.yml

@vgvassilev could you suggest a way to resolve the CMake error, already tried sudo command to install all required libraries yet facing the same issue

Run clang-tidy on PR

---

.clang-tidy
include/clang/Interpreter/Compatibility.h
include/clang/Interpreter/CppInterOp.h
include/clang/Interpreter/CppInterOpInterpreter.h
lib/Interpreter/CppInterOp.cpp
unittests/CppInterOp/CMakeLists.txt
unittests/CppInterOp/CUDATest.cpp

This patch allows us to bootstrap the infrastructure to process cuda code incrementally.

[cuda] Add support for CUDA.

---

unittests/CppInterOp/CUDATest.cpp

This reverts commit bcd51b7b00a9df4121f86673b552241d6a0c93b4 which was accidentally merged.

Revert "Debug"

---

.github/workflows/ci.yml
.github/workflows/clang-format.yml
unittests/CppInterOp/FunctionReflectionTest.cpp
unittests/CppInterOp/JitTest.cpp
unittests/CppInterOp/ScopeReflectionTest.cpp
unittests/CppInterOp/TypeReflectionTest.cpp

- Added steps to build LLVM/clang on macOS and works perfectly
- Errors are being faced while building and testing CppInterop hence needs to be fixed yet

Updating CI with macOS build

---

README.md

@vgvassilev This PR updates the build instructions in the README . I checked against the ci to make sure it is consistent between the 2.

Update README.md build instructions to fix typos and mistakes

---

.github/workflows/ci.yml

Adds the `--show-error-list=yes` flag to the valgrind command

[ci] Show error on valgrind

---

.github/workflows/ci.yml

@vgvassilev This PR will bring back the osx x86 jobs. Before merging, you may want to delete the osx x86 cache that this PR will make since it will no longer be in the main.

Add back osx x86 jobs to ci

---

README.md

This PR updates the README.md build instructions to be closer to ci build instructions.

Update README.md build instructions to be closer to ci build instructions

---

README.md

-This PR corrects a spelling error in the README.md file.

 Spelling error in README.md

---

.github/workflows/stale-pr-and-issues.yml

I accidentally repeated labels in the stale issue and pr workflow. This PR corrects this.

Update labels for stale prs in stale-pr-and-issues.yml

---

docs/ReleaseNotes.md

This PR is a small update to the release notes to reflect that we have llvm 19 support.

Update ReleaseNotes.md to reflect llvm 19 support

---

.github/workflows/deploy-pages.yml

This PR should fix the workflow which deploys our Github page xeus-cpp example. These issues didn't show until it was attempted to run on the main.

Fix deploy-pages.yml

---

.github/workflows/deploy-pages.yml

In our current Github page it was forgotten to install the xeus-cpp kernel. It should now appear in our Github page after this PR is merged.

Update deploy-pages.yml to install xeus-cpp kernel

---

.github/workflows/ci.yml

This PR should hopefully reduce the cache size, hopefully allowing space for more llvm versions before we fill up the cache. I have deleted 2 jobs from the cache before creating this PR to see whether it works.

Reduce cache size

---

.github/workflows/ci.yml

This PR will fix the recently broken llvm cache for cling by including the utils folder needed for gtest.

Fix cling llvm cache

---

README.md
docs/DevelopersDocumentation.rst
docs/InstallationAndUsage.rst

This is the non wasm counterpart to this PR https://github.com/compiler-research/CppInterOp/pull/390 which updated added wasm instructions.

Update non wasm build instructions

---

.github/workflows/emscripten.yml
.github/workflows/non-emscripten.yml
README.md

This PR will separate the emscripten and non emscripten builds into separate workflows, to make them easier to maintain and update.

Separate out emscripten and non emscripten builds into separate workfows

---

.github/workflows/deploy-pages.yml
.github/workflows/emscripten.yml

Fix emscripten build ci and deployment

---

.github/workflows/deploy-pages.yml
.github/workflows/emscripten.yml

Attempt to fix emscripten build

---

.github/workflows/deploy-pages.yml

Attempt to fix emscripten deployment

---

.github/workflows/deploy-pages.yml

Fixed shared library location xeus-cpp deployment

---

.github/workflows/deploy-pages.yml

This should be merged after https://github.com/compiler-research/xeus-cpp/pull/207 so that both only use the notebook that fully works.

Reference notebook where everything is known to work

---

.github/workflows/deploy-pages.yml

This PR adds jupyter notebook view as alternative to jupyter lab view in the deployment, fixing some other warnings in the jupyter lite build too.

Add jupyter notebook view as alternative to jupyter lab in deployment

---

.github/workflows/deploy-pages.yml
.github/workflows/emscripten.yml

By shallow cloning emsdk in the emscripten build we should have a tiny bit of time, but time amount of time add up.

Shallow clone emsdk

---

.github/workflows/MacOS.yml
.github/workflows/Ubuntu.yml
.github/workflows/Windows.yml
.github/workflows/emscripten.yml

When building llvm the cppyy option has bearing on the outcome. This PR removes the cppyy option llvm build stage matrix.

Remove cppyy options llvm build stage ci

---

.github/workflows/deploy-pages.yml

Now that we have a working xeus-cpp-lite build we will want a nightly deployment of a new Github page, so we can pick up any new changes in the xeus-cpp repo.

Add nightly build forndeployment workflow

---

.github/workflows/MacOS.yml

This does the same as https://github.com/compiler-research/CppInterOp/pull/472 but for the MacOS builds.

Reduce MacOS cache size by not including benchmarks, examples and tests

---

.github/workflows/Ubuntu.yml

This reverts commit f43164cb943451920f98f20d12482821833a0395.

Fix mistake added to main for Valgrind

---

.github/workflows/Ubuntu.yml
.github/workflows/emscripten.yml

This PR adds Ubuntu 24.04 x86 runners to CppInterOps Ubuntu.yml workflow. 

Add Ubuntu 24.04 x86 runners to ci

---

.github/workflows/deploy-pages.yml

The example notebook CppInterOp deploys doesn't currently have all the material needed to work. This PR adds the needed material.

Add content to deployment needed to use all of demo notebook

---

.github/workflows/MacOS.yml

This is the same as https://github.com/compiler-research/CppInterOp/pull/476 but for MacOS.

Remove unneeded built tools and compile_commands.json build.ninja MacOS ci

---

README.md

This fixes the Ubuntu arm badge in the readme so it correctly displays Ubuntu arm.

Fix Ubuntu arm badge

---

.github/workflows/Ubuntu-arm.yml
.github/workflows/Ubuntu.yml

Update codecov/codecov-action to v5 ci

---

.github/workflows/Ubuntu.yml

Now that support for Ubuntu 24.04 x86 has been added to cppyy we can turn it on in the CppInterop Ubuntu.yml workflow.

Turn on cppyy for Ubuntu 24.04 x86 jobs

---

.github/workflows/Ubuntu-arm.yml

Now that support for Ubuntu 24.04 arm has been added to cppyy we can turn it on in the CppInterop Ubuntu-arm.yml workflow.

Turn on Ubuntu 24.04 arm cppyy jobs ci

---

lib/Interpreter/CMakeLists.txt

With the llvm change now part of llvm 20, and the Emscripten PR merged these FIXME statements should be able to be removed now.

Remove fixed FIXMEs Emscripten shared library build

---

unittests/CppInterOp/FunctionReflectionTest.cpp

Adds tests for nested constructor calls through `Cpp::Construct`

Add tests for nested constructor calls via `Cpp::Construct`

---

environment-wasm.yml

See https://github.com/compiler-research/xeus-cpp/pull/286 for more context

Pinning nlohmann_json version for xeus-cpp-lite

---

.github/workflows/Ubuntu-arm.yml
.github/workflows/Ubuntu.yml

To be merged after https://github.com/compiler-research/cppyy/pull/145

[ci] Configure valgrind suppressions for Cling 1.2

---

.github/actions/Build_and_Test_cppyy/action.yml

set `IS_VALGRIND` envrionment variable

---

docs/DebuggingCppInterOp.rst
docs/index.rst

Documentation for debugging CppInterOp using LLDB added.

Documentation for debugging CppInterOp using LLDB

---

.github/actions/Miscellaneous/Select_Default_Build_Type/action.yml

Fix ncpus environment variable ci

---

unittests/CppInterOp/ScopeReflectionTest.cpp
unittests/CppInterOp/TypeReflectionTest.cpp

From https://github.com/root-project/root/pull/18993

[test] Improve struct size check for 32-bit and MSVC double alignment

---

.github/workflows/emscripten.yml

Detect Windows Emscripten test failures

---

lib/CppInterOp/CppInterOp.cpp
unittests/CppInterOp/FunctionReflectionTest.cpp

Do not specify the template arguments explicitly
1 test in cppyy

fix codegen for template operator

---

lib/CppInterOp/Compatibility.h
lib/CppInterOp/CppInterOp.cpp
unittests/CppInterOp/ScopeReflectionTest.cpp

fix GetNumBases to handle templated typedefs

---

lib/CppInterOp/CppInterOp.cpp
unittests/CppInterOp/FunctionReflectionTest.cpp

fix GetFunctionAddress for templated functions

---

.github/actions/Miscellaneous/Install_Dependencies/action.yml
.github/workflows/emscripten.yml

This should allow the ci to be green.

Fix MacOS jobs ci
